spring.application.name=Agric-TechConnect
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.port=${PORT:8080}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# === MAIL ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

flutterwave.secret-key=${FLW_SECRET_KEY}
flutterwave.public-key=${FLW_PUBLIC_KEY}
flutterwave.secret-hash=${FLW_SECRET_HASH}
flutterwave.base-url=https://api.flutterwave.com
flutterwave.redirect-url=https://techconnect2.fly.dev/api/payments/callback

app.frontend-base-url=https://creator-connect-c59u.vercel.app

flutterwave.transfer-callback-url=https://techconnect2.fly.dev/api/withdrawals/webhook
flutterwave.transfer-currency=NGN



